module top_module_ahb (
    input HCLK,
    input HRESETn,
    input start,
    input [31:0] start_addr,
    input [2:0] burst_mode,
    input [2:0] transfer_size,
    input write_en,
    input [31:0] write_data,
    output [31:0] read_data
);

    wire [31:0] HADDR;
    wire [31:0] HWDATA;
    wire HWRITE;
    wire [1:0] HTRANS;
    wire [2:0] HBURST;
    wire [2:0] HSIZE;
    
    wire HREADY_OUT_TO_MASTER; 
    wire HREADY_IN_TO_SLAVES;  
    
    wire HRESP;
    wire [31:0] HRDATA;

    wire HSEL_S0, HSEL_S1, HSEL_S2, HSEL_S3, HSEL_S4, HSEL_S5, HSEL_S6, HSEL_S7, HSEL_DEF;

    wire [31:0] SLAVE0_HRDATA, SLAVE1_HRDATA, SLAVE2_HRDATA, SLAVE3_HRDATA;
    wire [31:0] SLAVE4_HRDATA, SLAVE5_HRDATA, SLAVE6_HRDATA, SLAVE7_HRDATA;
    wire [31:0] DEF_HRDATA;

    wire SLAVE0_HRESP, SLAVE1_HRESP, SLAVE2_HRESP, SLAVE3_HRESP;
    wire SLAVE4_HRESP, SLAVE5_HRESP, SLAVE6_HRESP, SLAVE7_HRESP;
    wire DEF_HRESP;

    wire SLAVE0_READYOUT, SLAVE1_READYOUT, SLAVE2_READYOUT, SLAVE3_READYOUT;
    wire SLAVE4_READYOUT, SLAVE5_READYOUT, SLAVE6_READYOUT, SLAVE7_READYOUT;
    wire DEF_READYOUT;

    assign HREADY_IN_TO_SLAVES = SLAVE0_READYOUT | SLAVE1_READYOUT | SLAVE2_READYOUT | SLAVE3_READYOUT | 
                                 SLAVE4_READYOUT | SLAVE5_READYOUT | SLAVE6_READYOUT | SLAVE7_READYOUT | 
                                 DEF_READYOUT;

    master_ahb u_master (
        .HCLK(HCLK),
        .HRESETn(HRESETn),
        .HREADY(HREADY_OUT_TO_MASTER), 
        .HRESP(HRESP),
        .HRDATA(HRDATA),

        .HADDR(HADDR),
        .HWDATA(HWDATA),
        .HWRITE(HWRITE),
        .HTRANS(HTRANS),
        .HBURST(HBURST),
        .HSIZE(HSIZE),

        .start(start),
        .start_addr(start_addr),
        .burst_mode(burst_mode),
        .transfer_size(transfer_size),
        .write_en(write_en),
        .write_data(write_data),
        .read_data(read_data)
    );

    decoder_ahb u_decoder (
        .HADDR(HADDR),
        .HREADY(HREADY_IN_TO_SLAVES), 
        
        .HSEL_SLAVE1(HSEL_S0),
        .HSEL_SLAVE2(HSEL_S1),
        .HSEL_SLAVE3(HSEL_S2),
        .HSEL_SLAVE4(HSEL_S3),
        .HSEL_SLAVE5(HSEL_S4),
        .HSEL_SLAVE6(HSEL_S5),
        .HSEL_SLAVE7(HSEL_S6),
        .HSEL_SLAVE8(HSEL_S7),
        .HSEL_DEFAULT(HSEL_DEF)
    );

    mux_ahb u_mux (
        .HSEL_S0(HSEL_S0),
        .HSEL_S1(HSEL_S1),
        .HSEL_S2(HSEL_S2),
        .HSEL_S3(HSEL_S3),
        .HSEL_S4(HSEL_S4),
        .HSEL_S5(HSEL_S5),
        .HSEL_S6(HSEL_S6),
        .HSEL_S7(HSEL_S7),
        .HSEL_DEF(HSEL_DEF),

        .SLAVE0_HRDATA(SLAVE0_HRDATA),
        .SLAVE1_HRDATA(SLAVE1_HRDATA),
        .SLAVE2_HRDATA(SLAVE2_HRDATA),
        .SLAVE3_HRDATA(SLAVE3_HRDATA),
        .SLAVE4_HRDATA(SLAVE4_HRDATA),
        .SLAVE5_HRDATA(SLAVE5_HRDATA),
        .SLAVE6_HRDATA(SLAVE6_HRDATA),
        .SLAVE7_HRDATA(SLAVE7_HRDATA),
        .DEF_HRDATA(DEF_HRDATA),
        
        .SLAVE0_HRESP(SLAVE0_HRESP),
        .SLAVE1_HRESP(SLAVE1_HRESP),
        .SLAVE2_HRESP(SLAVE2_HRESP),
        .SLAVE3_HRESP(SLAVE3_HRESP),
        .SLAVE4_HRESP(SLAVE4_HRESP),
        .SLAVE5_HRESP(SLAVE5_HRESP),
        .SLAVE6_HRESP(SLAVE6_HRESP),
        .SLAVE7_HRESP(SLAVE7_HRESP),
        .DEF_HRESP(DEF_HRESP),
        
        .SLAVE0_READY(SLAVE0_READYOUT),
        .SLAVE1_READY(SLAVE1_READYOUT),
        .SLAVE2_READY(SLAVE2_READYOUT),
        .SLAVE3_READY(SLAVE3_READYOUT),
        .SLAVE4_READY(SLAVE4_READYOUT),
        .SLAVE5_READY(SLAVE5_READYOUT),
        .SLAVE6_READY(SLAVE6_READYOUT),
        .SLAVE7_READY(SLAVE7_READYOUT),
        .DEF_READY(DEF_READYOUT),

        .HRDATA(HRDATA),
        .HRESP(HRESP),
        .HREADY(HREADY_OUT_TO_MASTER) 
    );

    slave_ahb S0 ( .HCLK(HCLK), .HRESETn(HRESETn), .HSEL(HSEL_S0), .HADDR(HADDR), .HWRITE(HWRITE), .HSIZE(HSIZE), .HBURST(HBURST), .HTRANS(HTRANS), .HWDATA(HWDATA), .HREADY(HREADY_IN_TO_SLAVES), .HREADYOUT(SLAVE0_READYOUT), .HRESP(SLAVE0_HRESP), .HRDATA(SLAVE0_HRDATA) );
    slave_ahb S1 ( .HCLK(HCLK), .HRESETn(HRESETn), .HSEL(HSEL_S1), .HADDR(HADDR), .HWRITE(HWRITE), .HSIZE(HSIZE), .HBURST(HBURST), .HTRANS(HTRANS), .HWDATA(HWDATA), .HREADY(HREADY_IN_TO_SLAVES), .HREADYOUT(SLAVE1_READYOUT), .HRESP(SLAVE1_HRESP), .HRDATA(SLAVE1_HRDATA) );
    slave_ahb S2 ( .HCLK(HCLK), .HRESETn(HRESETn), .HSEL(HSEL_S2), .HADDR(HADDR), .HWRITE(HWRITE), .HSIZE(HSIZE), .HBURST(HBURST), .HTRANS(HTRANS), .HWDATA(HWDATA), .HREADY(HREADY_IN_TO_SLAVES), .HREADYOUT(SLAVE2_READYOUT), .HRESP(SLAVE2_HRESP), .HRDATA(SLAVE2_HRDATA) );
    slave_ahb S3 ( .HCLK(HCLK), .HRESETn(HRESETn), .HSEL(HSEL_S3), .HADDR(HADDR), .HWRITE(HWRITE), .HSIZE(HSIZE), .HBURST(HBURST), .HTRANS(HTRANS), .HWDATA(HWDATA), .HREADY(HREADY_IN_TO_SLAVES), .HREADYOUT(SLAVE3_READYOUT), .HRESP(SLAVE3_HRESP), .HRDATA(SLAVE3_HRDATA) );
    slave_ahb S4 ( .HCLK(HCLK), .HRESETn(HRESETn), .HSEL(HSEL_S4), .HADDR(HADDR), .HWRITE(HWRITE), .HSIZE(HSIZE), .HBURST(HBURST), .HTRANS(HTRANS), .HWDATA(HWDATA), .HREADY(HREADY_IN_TO_SLAVES), .HREADYOUT(SLAVE4_READYOUT), .HRESP(SLAVE4_HRESP), .HRDATA(SLAVE4_HRDATA) );
    slave_ahb S5 ( .HCLK(HCLK), .HRESETn(HRESETn), .HSEL(HSEL_S5), .HADDR(HADDR), .HWRITE(HWRITE), .HSIZE(HSIZE), .HBURST(HBURST), .HTRANS(HTRANS), .HWDATA(HWDATA), .HREADY(HREADY_IN_TO_SLAVES), .HREADYOUT(SLAVE5_READYOUT), .HRESP(SLAVE5_HRESP), .HRDATA(SLAVE5_HRDATA) );
    slave_ahb S6 ( .HCLK(HCLK), .HRESETn(HRESETn), .HSEL(HSEL_S6), .HADDR(HADDR), .HWRITE(HWRITE), .HSIZE(HSIZE), .HBURST(HBURST), .HTRANS(HTRANS), .HWDATA(HWDATA), .HREADY(HREADY_IN_TO_SLAVES), .HREADYOUT(SLAVE6_READYOUT), .HRESP(SLAVE6_HRESP), .HRDATA(SLAVE6_HRDATA) );
    slave_ahb S7 ( .HCLK(HCLK), .HRESETn(HRESETn), .HSEL(HSEL_S7), .HADDR(HADDR), .HWRITE(HWRITE), .HSIZE(HSIZE), .HBURST(HBURST), .HTRANS(HTRANS), .HWDATA(HWDATA), .HREADY(HREADY_IN_TO_SLAVES), .HREADYOUT(SLAVE7_READYOUT), .HRESP(SLAVE7_HRESP), .HRDATA(SLAVE7_HRDATA) );

    slave_ahb S_DEF (
        .HCLK(HCLK),
        .HRESETn(HRESETn),
        .HSEL(HSEL_DEF),
        .HADDR(HADDR),
        .HWRITE(HWRITE),
        .HSIZE(HSIZE),
        .HBURST(HBURST),
        .HTRANS(HTRANS),
        .HWDATA(HWDATA),
        .HREADY(HREADY_IN_TO_SLAVES),
        .HREADYOUT(DEF_READYOUT),
        .HRESP(DEF_HRESP),
        .HRDATA(DEF_HRDATA)
    );

endmodule